INCLUDE(FindPkgConfig)
PKG_CHECK_MODULES(PC_GNURADIO_OP25 gnuradio-op25)

FIND_PATH(
    GNURADIO_OP25_INCLUDE_DIRS
    NAMES op25/api.h
    HINTS $ENV{GNURADIO_OP25_DIR}/include
        ${PC_GNURADIO_OP25_INCLUDEDIR}
    PATHS /usr/local/include
          /usr/include
)

FIND_LIBRARY(
    GNURADIO_OP25_LIBRARIES
    NAMES gnuradio-op25
    HINTS $ENV{GNURADIO_OP25_DIR}/lib
        ${PC_GNURADIO_OP25_LIBDIR}
    PATHS /usr/local/lib
          /usr/local/lib64
          /usr/lib
          /usr/lib64
)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(GNURADIO_OP25 DEFAULT_MSG GNURADIO_OP25_LIBRARIES GNURADIO_OP25_INCLUDE_DIRS)
MARK_AS_ADVANCED(GNURADIO_OP25_LIBRARIES GNURADIO_OP25_INCLUDE_DIRS)
